/**
 * x402 Protocol Implementation
 *
 * ⚠️  SIMULATION NOTICE ⚠️
 * The PAYMENT VERIFICATION step is simulated in this implementation.
 * The x402 protocol spec, 402 HTTP responses, and payment headers are REAL.
 * The on-chain payment broadcast and verification are simulated because:
 *   1. x402 SDKs require browser/wallet context not available server-side
 *   2. The bounty spec explicitly allows simulated x402 if documented
 *
 * In production, replace `verifyPaymentProof()` with:
 *   import { verify } from "@x402/sdk";
 *   const valid = await verify(paymentProof, requirements);
 *
 * Spec: https://www.x402.org/
 */

import { createHash } from "crypto";

export interface X402PaymentRequirements {
  scheme: "exact";
  network: "solana-mainnet";
  maxAmountRequired: string; // lamports as string
  resource: string;
  description: string;
  mimeType: string;
  payTo: string;
  maxTimeoutSeconds: number;
  asset: "SOL";
  extra?: Record<string, unknown>;
}

export interface X402PaymentProof {
  network: string;
  paymentHash: string;
  payerWallet: string;
  amountLamports: string;
  resource: string;
  timestamp: number;
}

const MARKETPLACE_WALLET = "GpXHXs5KfzfXbNKcMLNbAMsJsgPsBE7y5GtwVoiuxYvH";
const LAMPORTS_PER_SOL = 1_000_000_000;

/**
 * Build the x402 payment requirements for an analysis.
 * These are returned in the 402 response headers.
 */
export function buildPaymentRequirements(
  analysisId: string,
  priceSol: number,
  analystWallet: string,
  description: string
): X402PaymentRequirements {
  return {
    scheme: "exact",
    network: "solana-mainnet",
    maxAmountRequired: String(Math.floor(priceSol * LAMPORTS_PER_SOL)),
    resource: `/analyses/${analysisId}`,
    description,
    mimeType: "application/json",
    payTo: analystWallet, // Analyst receives payment directly
    maxTimeoutSeconds: 300,
    asset: "SOL",
    extra: {
      marketplaceWallet: MARKETPLACE_WALLET,
      marketplaceFeePercent: 5,
      note: "5% marketplace fee collected by analyst on settlement",
    },
  };
}

/**
 * Build a simulated payment proof ticket.
 * In production, this is generated by the client-side x402 SDK after
 * broadcasting a real Solana transaction.
 *
 * ⚠️ SIMULATED: This generates a deterministic hash for demo purposes.
 */
export function buildSimulatedPaymentProof(
  buyerWallet: string,
  analysisId: string,
  amountSol: number
): X402PaymentProof {
  const timestamp = Date.now();
  // Simulated tx hash — in production this is a real Solana signature
  const paymentHash = createHash("sha256")
    .update(`SIM:${buyerWallet}:${analysisId}:${timestamp}`)
    .digest("hex");

  return {
    network: "solana-mainnet",
    paymentHash,
    payerWallet: buyerWallet,
    amountLamports: String(Math.floor(amountSol * LAMPORTS_PER_SOL)),
    resource: `/analyses/${analysisId}`,
    timestamp,
  };
}

/**
 * Verify a payment proof.
 *
 * ⚠️ SIMULATED: Checks proof structure and format only.
 * Production: would call Solana RPC to verify transaction finality
 * and that the correct amount was sent to the analyst's wallet.
 */
export function verifyPaymentProof(
  proof: X402PaymentProof,
  requirements: X402PaymentRequirements
): { valid: boolean; reason?: string } {
  // Structural validation (real)
  if (!proof.paymentHash || proof.paymentHash.length < 32) {
    return { valid: false, reason: "Invalid payment hash format" };
  }
  if (!proof.payerWallet || proof.payerWallet.length < 32) {
    return { valid: false, reason: "Invalid payer wallet" };
  }
  if (proof.resource !== requirements.resource) {
    return { valid: false, reason: "Resource mismatch" };
  }
  if (BigInt(proof.amountLamports) < BigInt(requirements.maxAmountRequired)) {
    return { valid: false, reason: "Insufficient payment amount" };
  }
  if (Date.now() - proof.timestamp > requirements.maxTimeoutSeconds * 1000) {
    return { valid: false, reason: "Payment proof expired" };
  }

  // ⚠️ SIMULATED: In production, verify on-chain:
  // const tx = await connection.getTransaction(proof.paymentHash);
  // assert(tx.meta.postBalances[destIdx] - tx.meta.preBalances[destIdx] >= requiredLamports);

  return { valid: true };
}

/** Format requirements as the X-Payment-Required HTTP header value */
export function formatX402Header(req: X402PaymentRequirements): string {
  return Buffer.from(JSON.stringify(req)).toString("base64");
}

/** Parse the X-Payment-Proof header */
export function parseProofHeader(header: string): X402PaymentProof | null {
  try {
    return JSON.parse(Buffer.from(header, "base64").toString()) as X402PaymentProof;
  } catch {
    return null;
  }
}
